kernels:
  - name: X6815B-NativeFix
    repo: https://github.com/Heskyyy/kernel-infinix-x6833b
    branch: main
    defconfig: mt6789_defconfig
    arch: arm64
    make_args: "-j64"
anykernel:
  repo: https://github.com/osm0sis/AnyKernel3
  branch: master
