name: private kernel
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git bc bison flex libssl-dev make
    - name: Build Kernel
      run: |
        ./build.sh
